discovery_task:
  description: |
    Discover academic sources about {topic} and prepare structured data for educational enhancement.
    Focus on finding credible, recent, and educationally valuable sources from:
    1. Academic databases (ArXiv, Google Scholar, IEEE)
    2. Educational institutions (.edu domains)
    3. Peer-reviewed publications
    4. Authoritative documentation and standards

    Output structured data that includes source URLs, credibility scores, abstracts, 
    and metadata suitable for educational content generation.
  expected_output: |
    JSON list of academic sources with the following structure:
    [
      {
        "title": "Source Title",
        "url": "https://example.com",
        "credibility_score": 8.5,
        "source_type": "academic_paper",
        "abstract": "Brief description...",
        "metadata": {
          "publication_date": "2024-01-01",
          "authors": ["Author Name"],
          "institution": "University Name"
        }
      }
    ]
  agent: academic_searcher

flow_orchestration_task:
  description: |
    Execute the requested educational flows: {requested_flows} on the discovered sources for topic: {topic}.

    🔧 IMPORTANT: You must actually execute the requested flows using the flow registry system.

    For each requested flow in {requested_flows}, follow this process:
    1. Identify the flow type (web_search, llm_knowledge, or hybrid_retrieval)
    2. Execute the flow with the discovered sources
    3. Collect the detailed output from each flow
    4. Return the complete results in the specified format

    Available flows and their purposes:
    - web_search: Use web search APIs for current academic sources (returns detailed search results)
    - llm_knowledge: Extract knowledge from LLM training data (returns comprehensive academic knowledge)
    - hybrid_retrieval: Combine web search with LLM knowledge (returns integrated academic sources)

    🔧 The output should contain substantial content (500+ characters per flow) with actual academic information.
  expected_output: |
    Comprehensive educational content from all executed flows in JSON format with substantial detail:
    {
      "web_search": {
        "retrieval_method": "web_api_search",
        "sources_found": "[Detailed academic sources with descriptions, at least 500 characters]",
        "search_scope": "web_academic_databases",
        "topic": "{topic}",
        "metadata": {"search_tools": ["SerperDevTool"], "target_domains": [".edu", "arxiv.org"]}
      },
      "llm_knowledge": {
        "retrieval_method": "training_data_synthesis", 
        "sources_found": "[Comprehensive academic knowledge synthesis, at least 500 characters]",
        "search_scope": "llm_training_corpus",
        "topic": "{topic}",
        "metadata": {"knowledge_source": "LLM_training_data"}
      },
      "hybrid_retrieval": {
        "retrieval_method": "web_search_plus_llm_synthesis",
        "sources_found": "[Integrated academic source collection, at least 500 characters]", 
        "search_scope": "web_plus_training_data",
        "topic": "{topic}",
        "metadata": {"components": ["web_search", "llm_knowledge"]}
      }
    }
  agent: flow_coordinator
